### ISSUE TITLE
苹果上点击无效，需要双击才能

### ISSUE THREAD

**Issue by google404** [LuckDraw/vue-luck-draw#15]

**Comment by buuing** [comment]
我看一下啊

**Comment by buuing** [comment]
我测了, 没问题啊, 你看你是不是用了什么插件, 比如fastclick之类的

**Comment by google404** [comment]
嗯，我发现是fastclick的问题了，转盘持续的时间有点长，我在尝试修改

**Comment by buuing** [comment]
> 嗯，我发现是fastclick的问题了，转盘持续的时间有点长，我在尝试修改

旋转的持续时间, 一是可能接口返回慢, 二是要等待完全加速之后才开始停止, 对此你可以微调一下速度 `defaultStyle.speed` 默认是20, 建议范围 10 ~ 30

**Comment by buuing** [comment]
> 嗯，我发现是fastclick的问题了，转盘持续的时间有点长，我在尝试修改

对了, `speed`速度是`v3.0.9`版本才加的, 建议你`npm i vue-luck-draw`更新一下, 用的顺手记得帮我点个星😇

**Comment by GongZhuoYing** [comment]
我使用大转盘抽奖插件，苹果手机上点击大转盘中间那个开始按钮，转盘不转

**Comment by buuing** [comment]
> 我使用大转盘抽奖插件，苹果手机上点击大转盘中间那个开始按钮，转盘不转

看一下你使用的插件的版本号发一下

**Comment by GongZhuoYing** [comment]
"vue": "^2.6.11",
"vue-luck-draw": "^1.2.2",
"vue-router": "^3.3.4",
"vuex": "^3.5.1"

**Comment by buuing** [comment]
> "vue": "^2.6.11",
> "vue-luck-draw": "^1.2.2",
> "vue-router": "^3.3.4",
> "vuex": "^3.5.1"

之前的版本确实有这个问题, 我建议通过更新版本 `v3.3.4` 来修复该问题, 但是小心语法变化

**Comment by GongZhuoYing** [comment]
多谢大佬！！！

**Comment by buuing** [comment]
> 多谢大佬！！！

小心语法变化, 现在的语法跟`1.x`相差过大, 如果遇到疑惑的地方可以询问
用的顺手可以点个 star 支持一下

**Comment by GongZhuoYing** [comment]
果真呀，以前我直接调用的<luckDraw>现在不行了。大转盘抽奖必须使用<luckyWheel>吗？

**Comment by buuing** [comment]
> 果真呀，以前我直接调用的现在不行了。大转盘抽奖必须使用吗？

你可以看一下现在的文档[100px.net](https://100px.net), 配置参数非常详细, 新增了很多属性

**Comment by GongZhuoYing** [comment]
谢谢指路，🙏

**Comment by xqp-ai** [comment]
> 嗯，我发现是快速点击的问题了，转盘持续的时间有点长，我在尝试修改

你好请问这个问题解决了吗

**Comment by buuing** [comment]
> 你好请问这个问题解决了吗

大哥你就看不到我在前面跟别人说的话吗?

**Comment by buuing** [comment]
> 你好请问这个问题解决了吗

这个问题升级最新版可以解决, 你用的啥版本?

**Comment by xqp-ai** [comment]
你好请问ios里为什么点击两下转盘才会转动啊

**Comment by xqp-ai** [comment]
你好请问ios里为什么点击两下转盘才会转动啊
