### ISSUE TITLE
大转盘可以配置旋转的时间吗

### ISSUE THREAD

**Issue by ha1ger** [LuckDraw/vue-luck-draw#17]
如题，目前开始旋转到结束要15秒左右的时间有点太久了
版本号3.14

**Comment by buuing** [comment]
> 如题，目前开始旋转到结束要15秒左右的时间有点太久了
> 版本号3.14

目前逻辑是这样的, 最少要等到完全旋转之后才慢慢停止, 默认速度为`20`, 目前你可以通过降低速度`defaultStyle.speed`来达到提前结束, 建议设置为`10`尝试一下

同时我也将会在`下一个版本`, 增加控制`旋转时间`的属性

**Comment by ha1ger** [comment]
> > 如题，目前开始旋转到结束要15秒左右的时间有点太久了
> > 版本号3.14
> 
> 目前逻辑是这样的, 最少要等到完全旋转之后才慢慢停止, 默认速度为`20`, 目前你可以通过降低速度`defaultStyle.speed`来达到提前结束, 建议设置为`10`尝试一下
> 
> 同时我也将会在`下一个版本`, 增加控制`旋转时间`的属性
好的，我试试

**Comment by yonghui666** [comment]
> > > 如题，目前开始旋转到结束要15秒左右的时间有点太久了
> > > 版本号3.14
> > 
> > 
> > 目前逻辑是这样的, 最少要等到完全旋转之后才慢慢停止, 默认速度为`20`, 目前你可以通过降低速度`defaultStyle.speed`来达到提前结束, 建议设置为`10`尝试一下
> > 同时我也将会在`下一个版本`, 增加控制`旋转时间`的属性
> > 好的，我试试

老哥；旋转时间可以配置了吗；着急用

**Comment by buuing** [comment]
> 老哥；旋转时间可以配置了吗；着急用

请描述一下你的需求, 是需要长时间旋转还是短时间旋转 ?

**Comment by buuing** [comment]
> 老哥；旋转时间可以配置了吗；着急用

如果是长时间旋转可以在start回调里面手动加一个定时器
短时间旋转我还在连着缓动函数一起重写
没办法, 最近公司业务比较多

**Comment by yonghui666** [comment]
> > 老哥；旋转时间可以配置了吗；着急用
> 
> 如果是长时间旋转可以在start回调里面手动加一个定时器
> 短时间旋转我还在连着缓动函数一起重写
> 没办法, 最近公司业务比较多

这个想让旋转时间短一点；有临时解决方案吗？急用

**Comment by buuing** [comment]
> 这个想让旋转时间短一点；有临时解决方案吗？急用

你用的是九宫格还是大转盘, 大转盘的旋转函数重构好了, 你加下我微信: `new_ldq`

**Comment by yonghui666** [comment]
> > 这个想让旋转时间短一点；有临时解决方案吗？急用
> 
> 你用的是九宫格还是大转盘, 大转盘的旋转函数重构好了, 你加下我微信: `new_ldq`

大转盘，老哥你微信搜不到啊；我微信：it_996

**Comment by buuing** [comment]
> 大转盘，老哥你微信搜不到啊；我微信：it_996

我加你了, 一直没反应
