### ISSUE TITLE
LuckyWheel-大转盘对移动端不是很友好

### ISSUE THREAD

**Issue by Im-SAMW** [LuckDraw/vue-luck-draw#18]
LuckyWheel-大转盘对移动端不是很友好，轻触不会启动转盘，需要快速点击2次；

应该需要加一个 touch 事件

**Comment by buuing** [comment]
嗯, 这个应该是fastClick之类的插件引起的, 我一会优化一下, 如果你不着急上线的话

**Comment by Im-SAMW** [comment]
我这边直接给整个 canvas 加了一个 touch 事件，简单粗暴

**Comment by buuing** [comment]
额, 这个fastclick我刚看了一下, 已经两年多没更新了, 我这里试了一些方案, 似乎都不能从插件内部解决该问题

**Comment by buuing** [comment]
> 我这边直接给整个 canvas 加了一个 touch 事件，简单粗暴

我这应该是修复该问题了, 一会我发布新版本告诉你, 你再试一下

**Comment by buuing** [comment]
> 我这边直接给整个 canvas 加了一个 touch 事件，简单粗暴

新版本`v3.1.7`已修复该问题, 你`npm i vue-luck-draw`更新版本看一下

**Comment by Im-SAMW** [comment]
> > 我这边直接给整个 canvas 加了一个 touch 事件，简单粗暴
> 
> 新版本`v3.1.7`已修复该问题, 你`npm i vue-luck-draw`更新版本看一下

收到，辛苦
