### ISSUE TITLE
3.14版本 当奖品列表只有两个奖品时，转盘会一直转 不会停下来。

### ISSUE THREAD

**Issue by lisf-ksk** [LuckDraw/vue-luck-draw#20]
3.14版本 当奖品列表只有两个奖品时，转盘会一直转 不会停下来。
prizes: [{
                            background: "#f8d384",
                            fonts: [{text: "1元红包", top: "8%"}],
                            imgs: [{src: i("083c"), width: "30%", top: "25%"}]
                        }, {
                            background: "#f9e3bb",
                            fonts: [{text: "100元红包", top: "8%"}],
                            imgs: [{src: i("2bd0"), width: "30%", top: "25%"}]
                        }]

**Comment by buuing** [comment]
稍等我看一下

**Comment by lisf-ksk** [comment]
> 稍等我看一下

你好 t.$refs.LuckyWheel.stop(2 * Math.random() >> 0) 我把这个8改成2 就可以了
但是我现在不知道该怎么把后台数据传递给prizes

**Comment by buuing** [comment]
哦哦哦, 那个 `Math.random() * 8 >> 0`是我在获取0~7的随机索引值, 因为你传递了不存在的奖品, 所以他无法停下来

**Comment by buuing** [comment]
后台给了你什么样的数据呢?

**Comment by lisf-ksk** [comment]
> 后台给了你什么样的数据呢?

后台我自己做的 json格式 但我有点看不懂这些参数。"083c": function (t, e, i) {
        t.exports = i.p + "img/0.efbe4dff.png"
    }
不知道该怎么传递数据给prizes[] 然后进行遍历

**Comment by buuing** [comment]
> 后台我自己做的 json格式 但我有点看不懂这些参数。"083c": function (t, e, i) {
> t.exports = i.p + "img/0.efbe4dff.png"
> }
> 不知道该怎么传递数据给prizes[] 然后进行遍历

首先, 你这个数据我也看不懂, 但你说后台是你自己做的, 那么你或许可以传递一个良好的json格式来解决该问题?
其次, 我不建议大转盘只放置小于等于两个奖品, 因为canvas绘制无法绘制大于等于180度的弧度...

**Comment by buuing** [comment]
如果无法处理后台数据的话, 那你也可以直接在`data`里面把`prizes`写死, 比如:
```js
      prizes: [
        {
          fonts: [{ text: '你的奖品文字' }],
          imgs: [{ src: '你的图片地址' }],
          background: '颜色',
        },
        {
          fonts: [{ text: '你的奖品文字' }],
          imgs: [{ src: '你的图片地址' }],
          background: '颜色',
        },
      ],
```

**Comment by lisf-ksk** [comment]
> > 后台我自己做的 json格式 但我有点看不懂这些参数。"083c": function (t, e, i) {
> > t.exports = i.p + "img/0.efbe4dff.png"
> > }
> > 不知道该怎么传递数据给prizes[] 然后进行遍历
> 
> 首先, 你这个数据我也看不懂, 但你说后台是你自己做的, 那么你或许可以传递一个良好的json格式来解决该问题?
> 其次, 我不建议大转盘只放置小于等于两个奖品, 因为canvas绘制无法绘制大于等于180度的弧度...

因为我的需求是 7种奖品共21个抽21次，当一个奖品抽完之后 数量为0时 我就需要重新渲染prizes里面的数据，就会减少一中奖品 所以会出现只剩2个奖品的情况，请问你的插件我修改一些代码后 可以实现这个功能吗？

**Comment by lisf-ksk** [comment]
> 如果无法处理后台数据的话, 那你也可以直接在`data`里面把`prizes`写死, 比如:
> 
> ```js
>       prizes: [
>         {
>           fonts: [{ text: '你的奖品文字' }],
>           imgs: [{ src: '你的图片地址' }],
>           background: '颜色',
>         },
>         {
>           fonts: [{ text: '你的奖品文字' }],
>           imgs: [{ src: '你的图片地址' }],
>           background: '颜色',
>         },
>       ],
> ```

这一点我担心使用的人不小心刷新了页面 然后，数据重新加载了，因为我的这个奖品时有数量要求的 ，抽中一次数量减-1 数量为0时移出奖品池。

**Comment by buuing** [comment]
哦哦, 你这个功能什么时候提测, 我优化一下代码, 预计明天会更新新版本

**Comment by lisf-ksk** [comment]
> 哦哦, 你这个功能什么时候提测, 我优化一下代码, 预计明天会更新新版本
好的 可以等到明天使用 麻烦您了.

**Comment by buuing** [comment]
没事, 你的需求还算合理, 这个弧度的问题也确实该优化一下了, 详细的问题你加我微信聊吧：`new_ldq`

**Comment by buuing** [comment]
最新版`v3.1.7`已修复不能绘制超过180度的扇形的问题
