### ISSUE TITLE
我想知道具体怎么适配移动端

### ISSUE THREAD

**Issue by yonghui666** [LuckDraw/vue-luck-draw#21]
使用rem，求告知

**Comment by buuing** [comment]
额, 我貌似没配置rem这个单位, 我想想怎么给你加进去

**Comment by yonghui666** [comment]
> 额, 我貌似没配置rem这个单位, 我想想怎么给你加进去

我看作者这个小插件的确挺优秀的；电脑端也挺好用的；但是移动端肯定需要做设配才能用；
![image](https://user-images.githubusercontent.com/49012394/97104443-d9fa0200-16ee-11eb-80a0-0ce0cc242f77.png)

**Comment by buuing** [comment]
哈哈, 感谢夸奖, rem单位的适配问题, 我会排在最高优先级来实现, 你的需求什么时候提测

**Comment by buuing** [comment]
> 我看作者这个小插件的确挺优秀的；电脑端也挺好用的；但是移动端肯定需要做设配才能用；

我预估了一下, 不出意外的话, 这两天应该就可以发布新版支持rem单位

**Comment by yonghui666** [comment]
> 哈哈, 感谢夸奖, rem单位的适配问题, 我会排在最高优先级来实现, 你的需求什么时候提测

我搜了好多抽奖的小插件，你的文档最全，功能也最多；你这个在改进改进；应该可以做到同类中最优秀的

**Comment by buuing** [comment]
> 我搜了好多抽奖的小插件，你的文档最全，功能也最多；你这个在改进改进；应该可以做到同类中最优秀的

最新版`v3.1.8`已更新, 增加了rem单位适配, `1rem = html根标签的fontSize`

哈哈, 这个确实, 外面的抽奖插件没发给我提供参考, 只能是看谁给提建议, 再跟进优化

**Comment by yonghui666** [comment]
> > 我搜了好多抽奖的小插件，你的文档最全，功能也最多；你这个在改进改进；应该可以做到同类中最优秀的
> 
> **最新版`v3.1.8`已更新, 增加了rem单位适配, `1rem = html根标签的fontSize`**
> 
> 哈哈, 这个确实, 外面的抽奖插件没发给我提供参考, 只能是看谁给提建议, 再跟进优化

非常感谢作者；亲测移动端可用！！祝愿作者升官发财 ，财源广进；

**Comment by kang558** [comment]
可以加个 fontWeight 字体粗细 功能吗？ 💯

**Comment by buuing** [comment]
> 可以加个 fontWeight 字体粗细 功能吗？ 💯

可以, 但是这个不急, 之后连着字体间距 letterSpacing 一起加

**Comment by buuing** [comment]
> 可以加个 fontWeight 字体粗细 功能吗？ 💯

最新版`v3.1.9`已增加`fontWeight`属性, 默认为`'400'`

**Comment by kang558** [comment]
> > 可以加个 fontWeight 字体粗细 功能吗？ 💯
> 
> 最新版`v3.1.9`已增加`fontWeight`属性, 默认为`'400'`

强！ 👍
