### ISSUE TITLE
activeStyle 添加缩放功能

### ISSUE THREAD

**Issue by kang558** [LuckDraw/vue-luck-draw#24]
抽奖中标，或者划过中标，希望可以进行缩放（放大效果）。这个怎么做呢？有相关配置吗

**Comment by buuing** [comment]
你是想在九宫格里面的中奖标记中放大奖品?

**Comment by buuing** [comment]
目前九宫格可以**在`prizes`奖品列表中, 配置图片的`activeSrc`属性**
当中奖标记停留 / 划过的时候, 会临时切换显示图片, 详细配置请在文档中搜索`activeSrc`

**Comment by kang558** [comment]
> 你是想在九宫格里面的中奖标记中放大奖品?

整个方块变大，包括文字，图片，类似css那种缩放（transform: scale(1.5)

**Comment by kang558** [comment]
> 目前九宫格可以**在`prizes`奖品列表中, 配置图片的`activeSrc`属性**
> 当中奖标记停留 / 划过的时候, 会临时切换显示图片, 详细配置请在文档中搜索`activeSrc`

这个貌似可以，但是没有那种缩放过渡效果

**Comment by buuing** [comment]
了解, 你想让整个方格变大, **后期我会考虑增加该属性, 当新版发布时我会在这里回复你**

**Comment by kang558** [comment]
> 了解, 你想让整个方格变大, **后期我会考虑增加该属性, 当新版发布时我会在这里回复你**

OK，期待大佬更新 👍  😘
