### ISSUE TITLE
还应该增加的抽奖类型

### ISSUE THREAD

**Issue by mablevi** [LuckDraw/vue-luck-draw#25]
还应该增加的抽奖类型：摇一摇和老虎机

**Comment by buuing** [comment]
嗯, 打算等过一阵把插件分离成`javascript`版, 然后同时支持`vue`和`react`, 整体拆分完成之后, 再添加新的抽奖插件类型

**Comment by mablevi** [comment]
加油。持续关注

**Comment by buuing** [comment]
> 加油。持续关注

好的
