### ISSUE TITLE
关于大转盘Fonts属性的

### ISSUE THREAD

**Issue by liuhu1172694787** [LuckDraw/vue-luck-draw#26]
可以看到您的fonts属性   需要的是一个数组值，里面支持修改字体颜色，样式等等，但是您的fonts中的text为什么接收的是以个数组呢，不应该是{ text: "1元红包", top: '10%',fontColor:"red"},
            { text: "100元红包", top: '10%',fontColor:"green"},
            { text: "0.5元红包", top: '10%',fontColor:"yellow"},
   这样嘛？不然字体的颜色和样式不可以区分修改，那些属性将没有意义了，  或许这个不是bug，但是我觉得这样可能更方便一点，希望您帮忙改一下

**Comment by liuhu1172694787** [comment]
期待大佬可以帮忙看一下这个问题~

**Comment by buuing** [comment]
fonts中的text属性接受的是一个string类型的值啊

**Comment by liuhu1172694787** [comment]
> fonts中的text属性接受的是一个string类型的值啊

sorry   刚才使用错误了，给大佬添了麻烦，  QAQ~

**Comment by buuing** [comment]
嗯嗯没事, 用的顺手可以帮我点个`star`😇
