### ISSUE TITLE
概率和接口问题

### ISSUE THREAD

**Issue by anrui0219** [LuckDraw/vue-luck-draw#27]
请问怎样可以配置概率  或者可不可以接口返回哪个值   之后转盘就转到哪个值

**Comment by anrui0219** [comment]
> 请问怎样可以配置概率 或者可不可以接口返回哪个值 之后转盘就转到哪个值

抱歉  看到文档了   知道怎么弄了  给力

**Comment by buuing** [comment]
在`stop`方法中传入中奖索引即可实现控制概率, 用的顺手可以**点个`star`支持一下**
