### ISSUE TITLE
play()方法可以设置开始旋转的速度吗？

### ISSUE THREAD

**Issue by jsonpeter** [LuckDraw/vue-luck-draw#30]
希望点击开始的 时候 可以快速旋转

**Comment by buuing** [comment]
> 希望点击开始的 时候 可以快速旋转

你是想让旋转速度快一些是吗, 看一下文档里面的`defaultConfig`有速度和旋转时间的相关配置

**Comment by jsonpeter** [comment]
看到了 ，accelerationTime ！ 秒回啊

**Comment by buuing** [comment]
> 看到了 ，accelerationTime ！ 秒回啊

嗯, 你们提问我微信会收到提示, 有问题随时问
