### ISSUE TITLE
默认配置defaultConfig

### ISSUE THREAD

**Issue by littlepino** [LuckDraw/vue-luck-draw#31]
传入开始旋转时间和缓慢旋转时间，没有生效，且直接调用stop停止旋转时，从开始到完全停止结束，有15S，不知道出现了什么问题

**Comment by buuing** [comment]
> 传入开始旋转时间和缓慢旋转时间，没有生效，且直接调用stop停止旋转时，从开始到完全停止结束，有15S，不知道出现了什么问题

方便贴一下代码吗, 我看看你怎么用的

**Comment by littlepino** [comment]
<lucky-wheel
        ref="LuckyWheel"
        style="width: 250px; height: 250px;margin-top:20px"
        :blocks="[
          { padding: '0px', background: '#fff' }
        ]"
        :prizes="prizes"
        :buttons="[
          {
            radius: '15px',background:'transparent',imgs:[{src:'../static/imgs/pointer.png',width:'40px',top:'-27px'}]
          }
        ]"
        
        @start="startCallBack"
        @end="endCallBack"
        :default-config="defaultConfig"
      />

      defaultConfig: {
        speed: 30,
        accelerationTime: 1000,
        decelerationTime: 1000,
        // offsetDegree: 90
      }
      methods: {
         startCallBack(){
            this.$refs.LuckyWheel.play()
            this.$refs.LuckyWheel.stop(Math.random() * 8 >> 0)
        }
      }

**Comment by buuing** [comment]
看一下你 `package.json` 里面的版本, 旋转速度是 `v3.2.1` 新增的两个属性

**Comment by littlepino** [comment]
嗯嗯，我刚刚看到，我装的版本是3.1.9,非常感谢您的回答，我去升级一下版本

**Comment by buuing** [comment]
> 嗯嗯，我刚刚看到，我装的版本是3.1.9,非常感谢您的回答，我去升级一下版本

好的, 用着顺手可以点个**star**支持一下

**Comment by littlepino** [comment]
> > 嗯嗯，我刚刚看到，我装的版本是3.1.9,非常感谢您的回答，我去升级一下版本
> 
> 好的, 用着顺手可以点个**star**支持一下

谢谢，已点
