### ISSUE TITLE
有计划开发老虎机 slot-machine 的计划么？

### ISSUE THREAD

**Issue by lizy0329** [LuckDraw/vue-luck-draw#32]
轮盘/九宫格/老虎机 都是互联网常见且固定的抽奖形式，将来有开发老虎机这方面的计划么？

**Comment by buuing** [comment]
> 轮盘/九宫格/老虎机 都是互联网常见且固定的抽奖形式，将来有开发老虎机这方面的计划么？

虽然有但是排的比较靠后, 目前正在使用`ts`分离逻辑, 然后基于原生版本来同时支持vue和react, 三端同时维护一套代码, 整体架构完成之后才会增加新的抽奖类型
