### ISSUE TITLE
圆形转盘img格式

### ISSUE THREAD

**Issue by Lee-42** [LuckDraw/vue-luck-draw#33]
请问在圆形转盘中的img支持传入的格式有哪些？除了本地可以，base64，blob可以吗？

**Comment by buuing** [comment]
> 请问在圆形转盘中的img支持传入的格式有哪些？除了本地可以，base64，blob可以吗？

你试试吧, base64应该可以, blob我不清楚

**Comment by buuing** [comment]
> 请问在圆形转盘中的img支持传入的格式有哪些？除了本地可以，base64，blob可以吗？

内部加载图片的逻辑, 是先`new`一个`img对象`然后为其添加`src`属性, 所以常规的图片引入方式都是可以的
