### ISSUE TITLE
页面不显示，控制台html有代码

### ISSUE THREAD

**Issue by David-cell-oss** [LuckDraw/vue-luck-draw#36]
第一步：npm i vue-luck-draw
第二部：main.js  里面
import LuckDraw from 'vue-luck-draw'
Vue.use(LuckDraw)
第三步：页面使用
<template>
  <div>
    
    <LuckyWheel
      style="width: 520px; height: 520px"
      v-model="currIndex"
      :awards="awards"
      :rate="rate"
      :radius="radius"
      :textFontSize="textFontSize"
      :lineHeight="lineHeight"
      :textColor="textColor"
      :textMargin="textMargin"
      :textPadding="textPadding"
      :btnFontSize="btnFontSize"
      :btnColor="btnColor"
      :btnBorderColor1="btnBorderColor1"
      :btnBorderColor2="btnBorderColor2"
      :btnBorderColor3="btnBorderColor3"
      :btnBgColor="btnBgColor"
      :btnText="btnText"
      :btnRadius="btnRadius"
      :borderColor="borderColor"
      @start="handleStart"
      @end="handleEnd"
    />
  </div>
</template>
<script>
export default {
  data () {
    return {
      currIndex: 0,               // 奖品的索引
      rate: 80,                   // 转盘速率
      radius: 180,                // 转盘半径
      textFontSize: '13px',       // 文字大小
      lineHeight: 20,             // 文字行高
      textColor: '#d64737',       // 文字颜色
      textMargin: 30,             // 文字距离边框距离
      textPadding: 0,             // 文字补偿宽度
      btnFontSize: '26px',        // 按钮文字大小
      btnColor: '#d64737',        // 按钮文件颜色
      btnBorderColor1: '#d64737', // 按钮外边框颜色
      btnBorderColor2: '#ffffff', // 按钮内边框颜色
      btnBorderColor3: '#f6c66f', // 按钮指针颜色
      btnBgColor: '#ffdea0',      // 按钮背景颜色
      btnText: '抽奖',            // 按钮内容
      btnRadius: 60,              // 按钮半径
      borderColor: '#d64737',     // 边框颜色
      awards: [                   // 奖品
        { name: '价值5988元华为 P30pro', color: '#f9e3bb' },
        { name: '价值398元车载空气净化器', color: '#f8d384' },
        { name: '价值25元百叶帘遮阳挡', color: '#f9e3bb' },
        { name: '16元油卡套餐红包', color: '#f8d384' },
        { name: '5元油卡直冲红包', color: '#f9e3bb' },
        { name: '3元话费直冲红包', color: '#f8d384' },
        { name: '价值32元重力感应手机支架', color: '#f9e3bb' },
        { name: '价值198元手提迷你车在保温冷藏箱', color: '#f8d384' },
      ],
    }
  },
  methods: {
    handleStart () {
      console.log('开始抽奖')
    },
    handleEnd (index) {
      alert('恭喜您抽到大奖, 奖品为' + this.awards[this.currIndex].name)
    }
  }
}
</script>

**Comment by David-cell-oss** [comment]
![image](https://user-images.githubusercontent.com/74691502/99609706-6330fa00-2a4b-11eb-944e-b41d3d6e9362.png)

**Comment by buuing** [comment]
...刚到公司....而且你这个用的不对

**Comment by buuing** [comment]
你的第三部错了, 用的之前1.x版本的老代码, 你应该从`https://100px.net`文档的demo里复制最新的代码

**Comment by buuing** [comment]
我给你写了个demo, 你看一下现在的属性

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div id="app">
    <lucky-wheel
      style="width: 310px; height: 310px"
      ref="LuckyWheel"
      :prizes="prizes"
      :default-style="defaultStyle"
      :blocks="blocks"
      :buttons="buttons"
      @start="startCallBack"
      @end="endCallBack"
    />
  </div>
  <script src="https://cdn.jsdelivr.net/npm/vue@2.6.9/dist/vue.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vue-luck-draw@3/dist/luckdraw.umd.min.js"></script>
  <script>
    new Vue({
      el: '#app',
      data () {
        return {
          prizes: [],
          defaultStyle: {
            fontColor: '#d64737',
            fontSize: '16px'
          },
          blocks: [
            { padding: '13px', background: '#d64737' }
          ],
          buttons: [
            { radius: '50px', background: '#d64737' },
            { radius: '45px', background: '#fff' },
            { radius: '41px', background: '#f6c66f', pointer: true },
            {
              radius: '35px', background: '#ffdea0',
              fonts: [{ text: '开始\n抽奖', top: -16 }]
            }
          ],
        }
      },
      mounted () {
        this.getPrizesList()
      },
      methods: {
        getPrizesList () {
          this.prizes = []
          let data = ['1元红包', '100元红包', '0.5元红包', '2元红包', '10元红包', '50元红包', '0.3元红包', '5元红包']
          data.forEach((item, index) => {
            this.prizes.push({
              title: item,
              background: index % 2 ? '#f9e3bb' : '#f8d384',
              fonts: [{ text: item, top: '20%' }],
            })
          })
        },
        startCallBack () {
          this.$refs.LuckyWheel.play()
          setTimeout(() => {
            this.$refs.LuckyWheel.stop(Math.random() * 8 >> 0)
          }, 3000)
        },
        endCallBack (prize) {
          alert(`恭喜你获得${prize.title}`)
        }
      }
    })
  </script>
</body>
</html>
```
