### ISSUE TITLE
里面抽奖的按钮可以设置多个吗

### ISSUE THREAD

**Issue by 824201769** [LuckDraw/vue-luck-draw#38]
![image](https://user-images.githubusercontent.com/30851691/100051082-ef7d5b80-2e55-11eb-91b7-a3c2dab15507.png)

**Comment by buuing** [comment]
你为什么会需要两个抽奖按钮呢

**Comment by buuing** [comment]
哦, 你可能是想通过不同按钮来触发不同方法
目前的play抽奖方法是公用的, 即便你分开两个按钮, 你也无法得知用户到底点击了哪一个
但是这个需求我后在后面进行优化
目前你可以通过外置按钮的方式来增加按钮

**Comment by 824201769** [comment]
好的

**Comment by buuing** [comment]
> 好的

用着顺手可以点个 star 支持一下

**Comment by buuing** [comment]
最新版九宫格抽奖已增加多按钮模式
