### ISSUE TITLE
抽奖次数问题

### ISSUE THREAD

**Issue by xuyifeng3610** [LuckDraw/vue-luck-draw#40]
怎么设置抽奖次数 如果是0次 就不能抽奖 要怎么配置

**Comment by buuing** [comment]
> 怎么设置抽奖次数 如果是0次 就不能抽奖 要怎么配置

我正好有一个demo示例, 是控制抽奖次数的
https://100px.net/demo/grid/yyjk.html
你仔细观察`luckyNum`的使用, 如果为零就不调用`play`方法即可

**Comment by xuyifeng3610** [comment]
我是大转盘的  bottons 有这些配置 ， 我要怎么在 computed里面改  
  buttons: [
        { radius: '50px', background: '#fff' },
        { radius: '45px', background: '#ff4a3f' },
        { radius: '41px', background: '#ff4a3f', pointer: true },
        {
          radius: '35px',
          background: '#f5be51',
          fonts: [
            { text: '抽奖', width: '65%', top: '-80%', fontColor: '#F04724', fontWeight: '700', fontSize: '24px' },
            { text: `${this.luckyNum}次机会`, width: '65%', top: '20%', fontColor: '#A6352E' }
          ]
        }
      ],

**Comment by buuing** [comment]
加我微信我给你看看: `new_ldq`
