### ISSUE TITLE
执行this.$refs.LuckDraw.play()报错

### ISSUE THREAD

**Issue by shenyixuanV1** [LuckDraw/vue-luck-draw#41]
star!!
请问执行 this.$refs.LuckDraw.play() 后报错，求大佬帮忙看看
Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.

**Comment by buuing** [comment]
我看看

**Comment by buuing** [comment]
把你的版本号和代码贴一下, 版本号找一下`vue-luck-draw`和`lucky-canvas`这两个包

**Comment by shenyixuanV1** [comment]
除了安装vue-luck-draw 之外，还需要安装lucky-canvas吗？

**Comment by buuing** [comment]
> 除了安装vue-luck-draw 之外，还需要安装lucky-canvas吗？

你不用手动安, 那个会作为依赖项加载, 这是为了后期增加react版本做的公共逻辑分离

**Comment by shenyixuanV1** [comment]
"vue-luck-draw": "^3.3.0",
代码是
<template>
<div class="drawcontent">
  <div class="draw-head">
    <div>
      <img class="draw-avater icon-avatar3" src="https://g.fp.ps.netease.com/cg-image/file/5d5fb4638b742736ea590398Oo9WQHcD02?fop=imageView/2/w/150/h/150">
      <p class="draw-nickname f12">帅哥哥</p>
    </div>
    <div>
      <a class="g-Btn g-Btn-green">我的奖品</a>
      <a class="g-Btn g-Btn-green">活动规则</a>
    </div>
  </div>

  <p>云游幸运抽</p>
  <p>好礼云中落，锦鲤畅快游</p>

   <LuckyGrid
      ref="LuckDraw"
      :style="style"
      :rows="rows"
      :cols="cols"
      :class="css"
      :blocks="blocks"
      :prizes="prizes"
      :button="button"
      :default-config="defaultConfig"
      :default-style="defaultStyle"
      :active-style="activeStyle"
      @start="startCallBack"
      @end="endCallBack"
    />

</div>
</template>

<script>
import _event from '@/utils/event'
export default {
  name : 'drawcontent',
  data () {
    return {
      luckyNum: 0,
      rows: 3,
      cols: 3,
      css: 'luckdrawbox',
      style:'width: 350px; height: 350px',
      defaultConfig: {
        gutter: 5,
      },
      blocks: [
        { padding: '1px', background: '#e2cea3', borderRadius: '13px' },
        { padding: '5px 0px', background: '#f3ecdc', borderRadius: '13px' },
        { padding: '1px', background: '#e2cea3', borderRadius: '8px' },
        { padding: '15px 10px', background: '#fffcf5', borderRadius: '8px' },
      ],
      prizes: [],
      button: {
        x: 1, y: 1,
        imgs: [{
          src: require('@/assets/img/icon_KBS_clickbutton_hovered.png'),
          width: '75%',
          top: '10%'
        }]
      },
      defaultStyle: {
        borderRadius: 8,
        background: 'pink',
        fontColor: 'red',
        fontSize: '14px',
      },
      activeStyle: {
        background: 'red',
        fontSize: '18px',
        fontColor: 'yellow'
      }
    }
  },
  components: {
    
  },
  methods: {
    onShow(options = {}) {
      this.css = options.css;
      this.rows = options.rows;
      this.cols = options.cols;
      this.style = options.style;
    },
    getPrizeList () {
      // 模拟接口请求奖品列表
      setTimeout(() => {
        const data = [
          { 
            name: '1元红包', 
            img: require('@/assets/img/icon_CP_display_bluray_normal.png'),
            activeImg: require('@/assets/img/icon_CP_display_bluray_hovered.png') 
          },
          { 
            name: '100元红包', 
            src: require('@/assets/img/icon_CP_display_high_normal.png'),
            activeImg: require('@/assets/img/icon_CP_display_high_hovered.png')
          },
          { 
            name: '0.5元红包', 
            src: require('@/assets/img/icon_CP_display_low_normal.png'),
            activeImg: require('@/assets/img/icon_CP_display_low_hovered.png')
          },
          { 
            name: '2元红包', 
            src: require('@/assets/img/icon_CP_display_middel_normal.png'),
            activeImg: require('@/assets/img/icon_CP_display_middle_hovered.png')
          },
          { 
            name: '10元红包', 
            src: require('@/assets/img/icon_CP_ExitG_normal.png'),
            activeImg: require('@/assets/img/icon_CP_ExitG_hovered.png')
          },
          { 
            name: '50元红包', 
            src: require('@/assets/img/icon_CP_full screen_normal.png'),
            activeImg: require('@/assets/img/icon_CP_full screen_hovered.png')
          },
          { 
            name: '0.3元红包', 
            src: require('@/assets/img/icon_CP_Keyboard_normal.png'),
            activeImg: require('@/assets/img/icon_CP_Keyboard_hovered.png')
          },
          { 
            name: '5元红包', 
            src: require('@/assets/img/icon_CP_display_bluray_normal.png'),
            activeImg: require('@/assets/img/icon_CP_display_bluray_hovered.png')
          }
        ]
        this.prizes = []
        this.luckyNum = 1
        let axis = [[0, 0], [1, 0], [2, 0], [2, 1], [2, 2], [1, 2], [0, 2], [0, 1]]
        for (let i = 0; i < 8; i++) {
          let item = data[i]
          this.prizes.push({
            index: i, x: axis[i][0], y: axis[i][1],
            fonts: [{ text: item.name, top: '72%' }],
            imgs: [{ src: item.img, activeSrc: item.activeImg, width: '55%', top: '10%' }]
          })
        }
      }, 0)
    },
    startCallBack () {
      if (!this.luckyNum) return alert('还剩0次抽奖机会')
      console.log('xxxxxxxxxxxx',this.$refs.LuckDraw)
      this.$refs.LuckDraw.play()
      setTimeout(() => {
        let random = Math.random() * 7 >> 0
        this.$refs.LuckDraw.stop(random)
      }, 2000)
    },
    endCallBack (prize) {
      console.log('endddddddddddddddddddd',prize)
      alert(`恭喜你获得大奖: xxx`)
      this.luckyNum--
    }
  },
  mounted () {
    this.getPrizeList()
    _event.$on('showluckdraw', this.onShow)
  },
  destroyed () {
    _event.$off('showluckdraw', this.onShow)
  }
}
</script>

**Comment by shenyixuanV1** [comment]
版本是 "vue-luck-draw": "^3.3.0",

<template>
<div class="drawcontent">
     <LuckyGrid
      ref="LuckDraw"
      :style="style"
      :rows="rows"
      :cols="cols"
      :class="css"
      :blocks="blocks"
      :prizes="prizes"
      :button="button"
      :default-config="defaultConfig"
      :default-style="defaultStyle"
      :active-style="activeStyle"
      @start="startCallBack"
      @end="endCallBack"
    />

</div>
</template>

<script>
export default {
  name : 'drawcontent',
  data () {
    return {
      luckyNum: 0,
      rows: 3,
      cols: 3,
      css: 'luckdrawbox',
      style:'width: 350px; height: 350px',
      defaultConfig: {
        gutter: 5,
      },
      blocks: [
        { padding: '1px', background: '#e2cea3', borderRadius: '13px' },
        { padding: '5px 0px', background: '#f3ecdc', borderRadius: '13px' },
        { padding: '1px', background: '#e2cea3', borderRadius: '8px' },
        { padding: '15px 10px', background: '#fffcf5', borderRadius: '8px' },
      ],
      prizes: [],
      button: {
        x: 1, y: 1,
        imgs: [{
          src: require('@/assets/img/icon_KBS_clickbutton_hovered.png'),
          width: '75%',
          top: '10%'
        }]
      },
      defaultStyle: {
        borderRadius: 8,
        background: 'pink',
        fontColor: 'red',
        fontSize: '14px',
      },
      activeStyle: {
        background: 'red',
        fontSize: '18px',
        fontColor: 'yellow'
      }
    }
  },
  components: {
    
  },
  methods: {
    onShow(options = {}) {
      this.css = options.css;
      this.rows = options.rows;
      this.cols = options.cols;
      this.style = options.style;
    },
    getPrizeList () {
      // 模拟接口请求奖品列表
      setTimeout(() => {
        const data = [
          { 
            name: '1元红包', 
            img: require('@/assets/img/icon_CP_display_bluray_normal.png'),
            activeImg: require('@/assets/img/icon_CP_display_bluray_hovered.png') 
          },
          { 
            name: '100元红包', 
            src: require('@/assets/img/icon_CP_display_high_normal.png'),
            activeImg: require('@/assets/img/icon_CP_display_high_hovered.png')
          },
          { 
            name: '0.5元红包', 
            src: require('@/assets/img/icon_CP_display_low_normal.png'),
            activeImg: require('@/assets/img/icon_CP_display_low_hovered.png')
          },
          { 
            name: '2元红包', 
            src: require('@/assets/img/icon_CP_display_middel_normal.png'),
            activeImg: require('@/assets/img/icon_CP_display_middle_hovered.png')
          },
          { 
            name: '10元红包', 
            src: require('@/assets/img/icon_CP_ExitG_normal.png'),
            activeImg: require('@/assets/img/icon_CP_ExitG_hovered.png')
          },
          { 
            name: '50元红包', 
            src: require('@/assets/img/icon_CP_full screen_normal.png'),
            activeImg: require('@/assets/img/icon_CP_full screen_hovered.png')
          },
          { 
            name: '0.3元红包', 
            src: require('@/assets/img/icon_CP_Keyboard_normal.png'),
            activeImg: require('@/assets/img/icon_CP_Keyboard_hovered.png')
          },
          { 
            name: '5元红包', 
            src: require('@/assets/img/icon_CP_display_bluray_normal.png'),
            activeImg: require('@/assets/img/icon_CP_display_bluray_hovered.png')
          }
        ]
        this.prizes = []
        this.luckyNum = 1
        let axis = [[0, 0], [1, 0], [2, 0], [2, 1], [2, 2], [1, 2], [0, 2], [0, 1]]
        for (let i = 0; i < 8; i++) {
          let item = data[i]
          this.prizes.push({
            index: i, x: axis[i][0], y: axis[i][1],
            fonts: [{ text: item.name, top: '72%' }],
            imgs: [{ src: item.img, activeSrc: item.activeImg, width: '55%', top: '10%' }]
          })
        }
      }, 0)
    },
    startCallBack () {
      if (!this.luckyNum) return alert('还剩0次抽奖机会')
      console.log('xxxxxxxxxxxx',this.$refs.LuckDraw)
      this.$refs.LuckDraw.play()
      setTimeout(() => {
        let random = Math.random() * 7 >> 0
        this.$refs.LuckDraw.stop(random)
      }, 2000)
    },
    endCallBack (prize) {
      console.log('endddddddddddddddddddd',prize)
      alert(`恭喜你获得大奖: xxx`)
      this.luckyNum--
    }
  },
  mounted () {
    this.getPrizeList()
    
  },
  destroyed () {
   
  }
}
</script>

**Comment by shenyixuanV1** [comment]
代码都是按照vue demo 的

**Comment by buuing** [comment]
我这里运行没问题...你加一下我的微信`new_ldq`

**Comment by shenyixuanV1** [comment]
好的，感谢大佬

**Comment by buuing** [comment]
该问题是由图片引入异常引起的, 如果大家碰到类似问题, 可以挨个先去掉, 看看是哪个图片引起的
