### ISSUE TITLE
我想让stop的持续时间久一些，需要怎么做呢？

### ISSUE THREAD

**Issue by feacx** [LuckDraw/vue-luck-draw#43]
`this.$refs.LuckyWheel.stop(Math.random() * 8 >> 0)`
这个结束的速度太快了，我想给用户一点刺激的紧迫感，应该如何改源码呢，没找到哎，谢谢亲

**Comment by buuing** [comment]
> `this.$refs.LuckyWheel.stop(Math.random() * 8 >> 0)`
> 这个结束的速度太快了，我想给用户一点刺激的紧迫感，应该如何改源码呢，没找到哎，谢谢亲

源码基于TS编译：[lucky-canvas](https://github.com/LuckDraw/lucky-canvas)
在 `slowDown` 方法里使用了张鑫旭大佬的 `tween.js` 的二次方缓动函数来实现的停止逻辑

**Comment by buuing** [comment]
我更建议你使用`defaultConfig.decelerationTime`来微调缓慢停止的事件，建议范围1000 ~ 5000

**Comment by feacx** [comment]
> 我更建议你使用`defaultConfig.decelerationTime`来微调缓慢停止时间，建议范围1000 ~ 5000
> 用着顺手可以点个 **star** 支持一下

可否给个
 `startCallBack () {
      this.$refs.LuckyWheel.play()
      setTimeout(() => {
        this.$refs.LuckyWheel.stop(Math.random() * 800 >> 0)
      }, 3300)
    },
    endCallBack (prize) {
      alert(`恭喜你获得${prize.title}`)
    },`
这两部分的demo呀

**Comment by feacx** [comment]
> 我更建议你使用`defaultConfig.decelerationTime`来微调缓慢停止时间，建议范围1000 ~ 5000
> 用着顺手可以点个 **star** 支持一下

谢谢大佬，可以了
