### ISSUE TITLE
大转盘不显示图片？

### ISSUE THREAD

**Issue by jerryyan1990** [LuckDraw/vue-luck-draw#44]
![微信截图_20201201115721](https://user-images.githubusercontent.com/12929365/100695644-9b7df400-33cc-11eb-804e-7d50320c25fb.png)
如图，通过接口拿到的奖品信息，里面有图片地址并且能够访问到图片，还有个本地base64的图片，结果转盘上不能显示图片。
同样的数据复制出来，写死数据，能够正常渲染。这是为什么啊？

**Comment by jerryyan1990** [comment]
@buuing

**Comment by buuing** [comment]
> @buuing

嗯, 我吃完午饭回去看看, 稍等

**Comment by buuing** [comment]
> @buuing

你发一下你处理异步数据的代码我看看是不是没有触发vue的响应式

**Comment by jerryyan1990** [comment]
@buuing 您好，我的函数调用是在mounted调用的，初始化data的时候给了个空数组。使用的是push方法修改奖品数组。我对比了下所有的示例，再修改数据前有个this.prizes = []的操作，我加上之后图片就正常显示了，不加就不会显示，这是为什么呢？
![微信截图_20201201143009](https://user-images.githubusercontent.com/12929365/100705419-20273d00-33e2-11eb-9ae7-d4c11bce0e31.png)

**Comment by jerryyan1990** [comment]
谢谢 问题暂时解决了。我自己去补习下知识。这个库太好用了，感谢你们的辛勤付出。

**Comment by buuing** [comment]
> 谢谢 问题暂时解决了。我自己去补习下知识。这个库太好用了，感谢你们的辛勤付出。

额? 我刚刚貌似覆盖了你的问题 ????
没事, 好用的话可以推荐给别人
关于这个问题, 你可以看一下vue2.x的响应式缺陷
