### ISSUE TITLE
接入webview初始化的时候图片不显示

### ISSUE THREAD

**Issue by miantuanlx** [LuckDraw/vue-luck-draw#45]
插件接入webview后，初始化的时候服务器图片不显示，第一次点击抽奖之后才会正常显示

**Comment by buuing** [comment]
> 插件接入webview后，初始化的时候服务器图片不显示，第一次点击抽奖之后才会正常显示

好的, 我看一下

**Comment by buuing** [comment]
> 插件接入webview后，初始化的时候服务器图片不显示，第一次点击抽奖之后才会正常显示

你是在环境下使用的, uni-app还是普通的vue页面, 用的哪个包

**Comment by buuing** [comment]
你好, vue项目中测试没问题, 能看到的话, 加我一下微信吧: `new_ldq`

**Comment by buuing** [comment]
...建议大家不要clone源码到项目中使用, 因为我有时会在`master`里面暂存脏代码, 可能会引起一些意料之外的问题
