### ISSUE TITLE
当抽奖完成后 ，需要重绘canvas中间的开始按钮 

### ISSUE THREAD

**Issue by jsonpeter** [LuckDraw/vue-luck-draw#48]
从新$set(this.btnConfig , "imgs" 修改图片路径，图片没有重绘成功，有没有手都冻调用update的接口

**Comment by buuing** [comment]
贴一下代码我看看

**Comment by jsonpeter** [comment]
this.$set(this.btnConfig , "imgs", [{ src: require("./statics/img/button-disable.png"), width: "65%", top: "22%" }])

**Comment by buuing** [comment]
........大哥, 代码多贴点, 不要钱, 我主要是想看 btnConfig 是什么

**Comment by buuing** [comment]
要不你加我微信`new_ldq`给我截个图发我

**Comment by buuing** [comment]
已复现, 外层的watch观察触发了, 但是`lucky-canvas`内层的watch观察未触发, 最新版`v3.3.3`已修复该问题
