### ISSUE TITLE
咨询移动端转盘停不下的问题

### ISSUE THREAD

**Issue by aeasy88** [LuckDraw/vue-luck-draw#50]
start() {
            luckyWheel.play();
            $.ajax(
                {
                    url: 'http://127.0.0.1:8080/stop',
                    async: false,
                    method: 'get',
                    datatype: "json",
                    success: function (data) {
                        stopnum = data.statu
                    },
                });
            setTimeout(() => {
                // luckyWheel.stop(Math.random() * 8 >> 0)
                luckyWheel.stop(stopnum)
            }, 3000)
        },
你好，请问这段代码在pc浏览器是可以的，但是在移动端点击抽奖后就停不下来，请给指点一下，问题出在哪里呢？

**Comment by buuing** [comment]
刚到公司, 我看一下

**Comment by buuing** [comment]
你这个代码不对劲昂, `luckyWheel.stop(stopnum)`扔到success的回调函数里面, 万一接口返回很慢, 你这个岂不是拿不到中奖索引

**Comment by buuing** [comment]
```js
start() {
  luckyWheel.play();
  $.ajax({
    url: 'http://127.0.0.1:8080/stop',
    async: false,
    method: 'get',
    datatype: "json",
    success: function (data) {
      setTimeout(() => {
        luckyWheel.stop(data.statu)
      }, 3000)
    },
  })
},
```

你这样试一下

**Comment by aeasy88** [comment]
非常感谢，找到问题了，是ip地址的问题，127.0.0.1不行，需要设置成内网ip地址

**Comment by buuing** [comment]
> 非常感谢，找到问题了，是ip地址的问题，127.0.0.1不行，需要设置成内网ip地址

好的, 但是你记得一定要放到success里面调用stop
