### ISSUE TITLE
background 属性 希望能支持图片

### ISSUE THREAD

**Issue by LoverJoker** [LuckDraw/vue-luck-draw#52]
- 版本号：v3.3.3

- 平台信息：原生开发，直接引入cdn js

- 详细描述：现在backfound 只支持颜色，希望能支持背景图

**Comment by buuing** [comment]
大转盘后续会增加整张背景图, 方便整张图的旋转, 如果是外侧的背景图, 你完全可以通过img然后定位过去

**Comment by LoverJoker** [comment]
sorry, 我的表述好像不是很清楚，我使用的是九宫格，我的意思是 增加宫格里面的背景.

**Comment by buuing** [comment]
> sorry, 我的表述好像不是很清楚，我使用的是九宫格，我的意思是 增加宫格里面的背景.

九宫格现在就可以啊

**Comment by LoverJoker** [comment]
``` js
prizes.push({
      name: item.name,
      index: i, x: axis[i][0], y: axis[i][1],
      background: 'url(./un_select.png)', // 或者 background: './un_select.png'
      fonts: [{ text: item.name, top: '70%' }],
      imgs: [{ src: item.img, width: '53%', top: '8%' }]
    })
```

我是这样设置的，是我用法有问题吗？

**Comment by LoverJoker** [comment]
是需要用 imgs 这个数组设置对吧。

**Comment by buuing** [comment]
background不能接收, 但是你通过细心的观察, 将会发现imgs是一个数组, 那将意味着可以放置多个图片, 然后你将会在文档里发现图片的宽高可以设置100%来铺满整个格子

**Comment by LoverJoker** [comment]
嗯，理解了。感谢您的插件。

**Comment by buuing** [comment]
ok, 感谢你的支持

**Comment by LoverJoker** [comment]
还有一个问题 activeStyle 中奖标记 好像没有图片这个属性。如果我想要中奖的时候替换图片怎么做呢。

**Comment by LoverJoker** [comment]
具体来说，希望游走的中奖标记 不是简单换颜色，而是替换图片或者有一个图片盖上去。

**Comment by buuing** [comment]
> 还有一个问题 activeStyle 中奖标记 好像没有图片这个属性。如果我想要中奖的时候替换图片怎么做呢。

那你将会在文档里发现imgs下不仅有src属性, 还有一个activeSrc属性, 我建议你先浏览一下文档`https://100px.net`

**Comment by LoverJoker** [comment]
好的，是我错了。谢谢。

**Comment by buuing** [comment]
> 好的，是我错了。谢谢。

.......
