### ISSUE TITLE
对于转盘上的单个奖品能否设置具体概率，或后台指定中某个商品前端能否指定中单个商品

### ISSUE THREAD

**Issue by zhuziyee** [LuckDraw/vue-luck-draw#54]
开发者你好，非常感谢提供的转盘组件，并且很好用，不过我这边想问一下，前端能否针对于单个商品进行概率的设置，或者通过后台获取到指定中奖某个商品，希望您能看到，谢谢~

**Comment by buuing** [comment]
> 开发者你好，非常感谢提供的转盘组件，并且很好用，不过我这边想问一下，前端能否针对于单个商品进行概率的设置，或者通过后台获取到指定中奖某个商品，希望您能看到，谢谢~

可以指定, 你看一下`stop`方法, 可以传中奖索引
