### ISSUE TITLE
抽奖能否做成响应式的？根据父级宽度变化大小

### ISSUE THREAD

**Issue by webmengliuyi** [LuckDraw/vue-luck-draw#57]
这样写
`<LuckyGrid
    width="100%"
    height="100%"
/>`无效

**Comment by buuing** [comment]
用`style`属性设置宽度`100%`, 然后下面的宽高属性去掉即可

**Comment by webmengliuyi** [comment]
亲测可以，   666   star一个 ，   `<LuckyGrid width="100%" height="100%" />`  这2个属性有点迷惑人

**Comment by buuing** [comment]
因为**小程序端无法通过`style`的百分比获取固定长宽来设置`canvas`,** 所以文档里是统一使用`width`和`height`属性的
另外感谢支持😎

**Comment by webmengliuyi** [comment]
还一个疑问，    抽奖按钮   ->     文字描述 -> （剩余2次抽奖）    
想把这个 （ **_2次_**）  文字加粗或者改变颜色  如何实现？

**Comment by buuing** [comment]
看一下文档, 按钮文字可以自由

**Comment by buuing** [comment]
> 还一个疑问， 抽奖按钮 -> 文字描述 -> （剩余2次抽奖）
> 想把这个 （ **_2次_**） 文字加粗或者改变颜色 如何实现？

你试试这样
```js
fonts: [
  { text: '剩余     抽奖' },
  { text: '2次' },
]
```

**Comment by webmengliuyi** [comment]
测试完成，  第一次用   很多地方在摸索，  很不错的插件，       目前发现  只有`top: **`属性    `left: **`还不能用，  文字必须居中， 有点不方便     例如   `fonts: [
  { text: '剩余    次抽奖' },
  { text: '2' },
]`

**Comment by buuing** [comment]
插件刚做出来仨月, 整体不是特别完善, 而且微信小程序那边的canvas一堆反人类的bug不修复, 很多东西得慢慢来

**Comment by webmengliuyi** [comment]
很不错的插件，     很接近完美了，     已经把这个集成到项目里了，   后续有问题再反馈

**Comment by buuing** [comment]
你们的抽奖设计图好看吗, 我正在收集一些好看的demo挂到官网进行展示

**Comment by webmengliuyi** [comment]
一般般   不亮眼    就是常规的那样式    链接怎么发你  这里面发不了截图，  不太会玩这个

**Comment by buuing** [comment]
加我微信吧`new_ldq`, 我瞅一瞅😆
