### ISSUE TITLE
抽奖停止的时候指针可以不指向扇形中间，而是在扇形区域内随机点么

### ISSUE THREAD

**Issue by cy102235** [LuckDraw/vue-luck-draw#58]

**Comment by buuing** [comment]
可以, 该需求会在后期支持, 停止角度范围自定义

**Comment by buuing** [comment]
最新版已发布, 增加 `defaultConfig.stopRange` 中奖的扇形区域的停止范围 *（默认为 0.8, 建议范围 0 ~ 0.9, 如果设置 1 可能会停在奖品边缘!）*
