### ISSUE TITLE
背景不支持自定义的图片吗？

### ISSUE THREAD

**Issue by lwjsw2320214** [LuckDraw/vue-luck-draw#59]
背景不支持自定义的图片吗？

**Comment by buuing** [comment]
目前背景可以在外面通过ing标签+css定位搞定，如果你是想配置一整个圆形来旋转的话，目前尚未支持，后期会考虑

**Comment by buuing** [comment]
最新版`v3.3.8`已发布, 增加了`blocks`引入图片并可以控制是否参与旋转, 稍后我会更新文档相关配置
