### ISSUE TITLE
奖品列表能设置点击回调吗？

### ISSUE THREAD

**Issue by a599155162** [LuckDraw/vue-luck-draw#61]
如题，希望奖品列表可以有点击事件
谢谢~

**Comment by buuing** [comment]
> 如题，希望奖品列表可以有点击事件
> 谢谢~

你是在什么场景下有的这个需求😥

**Comment by a599155162** [comment]
> 

就是喜欢点击奖品，查看奖品详细信息。

**Comment by buuing** [comment]
哦, web端这边没问题, 但是`uni-app`那边会有兼容问题, 不支持`isPointInPath`这个API

**Comment by a599155162** [comment]
> 哦, web端这边没问题, 但是`uni-app`那边会有兼容问题, 不支持`isPointInPath`这个API

谢谢， 请问怎么实现呢？目前我是用在了web端

**Comment by buuing** [comment]
额我的意思是, 你这个需求可以实现, 但需要我后期新增方法😛

**Comment by a599155162** [comment]
> 额我的意思是, 你这个需求可以实现, 但需要我后期新增方法😛

非常感谢~ :D

**Comment by chentogit** [comment]
> 额我的意思是, 你这个需求可以实现, 但需要我后期新增方法😛

这个功能有实现吗？web端的奖品点击回调。

**Comment by buuing** [comment]
> 这个功能有实现吗？web端的奖品点击回调。

没有, 因为小程序不支持点击, 为了多端一致性, web端没做这个回调

**Comment by buuing** [comment]
在2.0里我在思考用其他方式来实现这个交互, 比如把dom交给使用者去渲染, 我只控制旋转和停止的逻辑

**Comment by EveWeiGit** [comment]
大佬，什么时候能支持奖品点击的回调(*╹▽╹*)
