### ISSUE TITLE
抽奖按钮文案是否支持rem单位

### ISSUE THREAD

**Issue by Cosimac** [LuckDraw/vue-luck-draw#62]
- 版本号："vue-luck-draw": "^3.3.5"

- 平台信息：移动端

- 详细描述：抽奖按钮的文案字体大小不支持fontSize: 18rem这样的写法有解决办法吗?  谢谢楼主

- 问题代码（最好同时包含 html 和 js）
```
button: {
        x: 1,
        y: 1,
        background: 'transparent',
        fonts: [{
          text: '11111',
          fontColor: '#fff',
          top: '25%',
          fontSize: '18px',
      }],
        imgs: []
      },
```

**Comment by buuing** [comment]
我记得好像支持的吧, 我测试一下啊

**Comment by buuing** [comment]
我这里测试没问题, 按钮文字支持`rem`属性 😎

**Comment by Cosimac** [comment]
> 我这里测试没问题，按钮文字支持`rem`属性😎

我试了没生效, 我再试下=-=

**Comment by Cosimac** [comment]
> 我这里测试没问题, 按钮文字支持`rem`属性 😎

楼主, 想问下你的写法是在配置里

**Comment by Cosimac** [comment]
楼主, 想问下你的写法是直接在配置里写`button: {
        x: 1,
        y: 1,
        background: 'transparent',
        fonts: [
          {
            text: '符合规定就是',
            fontColor: '#fff',
            top: '25%',
            fontSize: '18rem',
            lengthLimit: '60%'
          }
        ],
        imgs: []
      }`     我这样直接写fontSize: '18rem',  会导致字体都显示不出来了, 并且没有报错

**Comment by buuing** [comment]
`18rem`会不会太大了? , 你要不先换成`1rem`试试

**Comment by Cosimac** [comment]
> `18rem`会不会太大了? , 你要不先换成`1rem`试试

哈哈哈可以了, 蒙圈了感谢楼主耐心解答, star已点, 看之前有人在issues里喷楼主很不合适, 楼主格局还是稳的一批, 感谢,

**Comment by buuing** [comment]
> 哈哈哈可以了, 蒙圈了感谢楼主耐心解答, star已点, 看之前有人在issues里喷楼主很不合适, 楼主格局还是稳的一批, 感谢,

谢谢支持 😁
