### ISSUE TITLE
为何引入过后页面上只有一个空的容器  没有内容

### ISSUE THREAD

**Issue by HBreaker** [LuckDraw/vue-luck-draw#63]
- 版本号：3.3.7

- 平台信息：

- 详细描述：

- 问题代码（最好同时包含 html 和 js）
```
// 在这里粘贴你的代码
```
<template>
  <div class="container" id="top">
    <LuckyGrid
      width="200px"
      height="200px"
      v-model="currIndex"
      :awards="awards"
      @start="handleStart"
      @end="handleEnd"
    />
  </div>
</template>

<script>
export default {
  name: 'Draw',
  data () {
    return {
      currIndex: 0,
      awards: [
        { name: '价值5988元华为 P30pro', color: '#f9e3bb' },
        { name: '价值398元车载空气净化器', color: '#f8d384' },
        { name: '价值25元百叶帘遮阳挡', color: '#f9e3bb' },
        { name: '16元油卡套餐红包', color: '#f8d384' },
        { name: '5元油卡直冲红包', color: '#f9e3bb' },
        { name: '3元话费直冲红包', color: '#f8d384' },
        { name: '价值32元重力感应手机支架', color: '#f9e3bb' },
        { name: '价值198元手提迷你车在保温冷藏箱', color: '#f8d384' }
      ]
    }
  },
  mounted () {
  },
  methods: {
    handleStart () {
      console.log('开始抽奖')
    },
    handleEnd (index) {
      alert('恭喜您抽到大奖, 奖品为' + this.awards[this.currIndex].name)
    }
  }
}
</script>

<style scoped>
.container {
  width: 100%;
  height: 100%;
  background: url('../../assets/img/drawbg.jpg') no-repeat;
  background-size: 100%;
}
</style>

**Comment by buuing** [comment]
你这个是早期`v1.x`的版本, 详细请参照新版使用`https://100px.net/demo/wheel/ymc.html`

**Comment by HBreaker** [comment]
> 你这个是早期`v1.x`的版本, 详细请参照新版使用https://100px.net/demo/wheel/ymc.html

**Comment by HBreaker** [comment]
文档我这边没法访问

**Comment by buuing** [comment]
> 文档我这边没法访问

为什么无法访问, 是打不开还是报错, 描述一下, 别只说结果

**Comment by HBreaker** [comment]
![image](https://user-images.githubusercontent.com/59952212/104297168-7fa65b80-54fd-11eb-8bfc-db09b003fa88.png)

**Comment by HBreaker** [comment]
打不开

**Comment by HBreaker** [comment]
无法访问此网站

**Comment by buuing** [comment]
> 打不开

这, 我是托管在giehub pages下面的, 你github都能访问, 为啥这个打不开?

**Comment by HBreaker** [comment]
这个我也不知道啊  我同事那边也无法访问

**Comment by HBreaker** [comment]
在手机上访问成功了  可能公司网络限制吧

**Comment by buuing** [comment]
> 在手机上访问成功了 可能公司网络限制吧

你们啥公司, 怎么这也拦截😥

**Comment by buuing** [comment]
> 这个我也不知道啊 我同事那边也无法访问

用着顺手可以点个`star`支持一下🤣

**Comment by HBreaker** [comment]
可以的

**Comment by buuing** [comment]
> 可以的

你可以手机开热点给电脑连接, 这样你应该就可以访问了

**Comment by HBreaker** [comment]
测试生效  可以的  谢谢

**Comment by HBreaker** [comment]
方便吗？

**Comment by buuing** [comment]
> 方便吗？

什么事

**Comment by buuing** [comment]
> 我这边用了大转盘后 页面刷新不了 一直在转圈

你的意思是页面卡死了?

**Comment by HBreaker** [comment]
是的

**Comment by buuing** [comment]
> 是的

代码我看看, 我怀疑你写了死循环

**Comment by HBreaker** [comment]
代码引的你的demo  代码

**Comment by HBreaker** [comment]
图片去掉了的

**Comment by HBreaker** [comment]
getPrizesList () {
      const prizes = []
      let data = ['1元红包', '100元红包', '0.5元红包', '2元红包', '10元红包', '50元红包', '0.3元红包', '5元红包']
      data.forEach((item, index) => {
        prizes.push({
          title: item,
          background: index % 2 ? '#f9e3bb' : '#f8d384',
          fonts: [{ text: item, top: '10%' }]
        })
      })
      this.prizes = prizes
    },
    startCallBack () {
      console.log('开始')
      this.$refs.LuckyWheel.play()
      setTimeout(() => {
        this.$refs.LuckyWheel.stop(Math.random() * 8 >> 0)
      }, 3000)
    },
    endCallBack (prize) {
      alert(`恭喜你获得${prize.title}`)
    }

**Comment by HBreaker** [comment]
prizes: [],
      defaultStyle: {
        fontColor: '#d64737',
        fontSize: '14px'
      },
      blocks: [
        { padding: '13px', background: '#d64737' }
      ],
      buttons: [
        { radius: '50px', background: '#d64737' },
        { radius: '45px', background: '#fff' },
        { radius: '41px', background: '#f6c66f', pointer: true },
        {
          radius: '35px',
          background: '#ffdea0'
          // imgs: [{ src: require('./hb.png'), width: '65%', top: '-50%' }]
        }
      ]

**Comment by HBreaker** [comment]
配置项

**Comment by buuing** [comment]
你这代码也不对其, 加我微信我看看`new_ldq`

**Comment by HBreaker** [comment]
加你了
