### ISSUE TITLE
奖品项，能设置背景为渐变色吗？

### ISSUE THREAD

**Issue by BoqinDu** [LuckDraw/vue-luck-draw#65]
- 版本号：

- 平台信息：

- 详细描述：

- 问题代码（最好同时包含 html 和 js）
```
// 在这里粘贴你的代码
```

**Comment by buuing** [comment]
设计图我看一下, 什么样子的渐变色

**Comment by BoqinDu** [comment]
![微信截图_20210114162633](https://user-images.githubusercontent.com/45166307/104564216-9bd50480-5685-11eb-818a-5943e0453035.png)

**Comment by BoqinDu** [comment]
就这个奖品项 红色渐变

**Comment by buuing** [comment]
可以实现, 但是这个功能还在测试中, 你的需求什么时候提测

**Comment by BoqinDu** [comment]
一周内

**Comment by BoqinDu** [comment]
其实也不急，我可以先设置为普通的颜色，等你渐变色版本上了之后，我再修改也不迟

**Comment by buuing** [comment]
不是, 实现方式不一样, 算了, 你加一下我微信, 我截图给你看`new_ldq`

**Comment by BoqinDu** [comment]
大佬你的微信号说一下

**Comment by buuing** [comment]
> 大佬你的微信号说一下

new_ldq
