### ISSUE TITLE
大佬您好，请问您的文档现在怎么打不开了呢？我想问一下奖品名称超出指定长度的处理

### ISSUE THREAD

**Issue by GongZhuoYing** [LuckDraw/vue-luck-draw#66]
- 版本号：

- 平台信息：

- 详细描述：

- 问题代码（最好同时包含 html 和 js）
```
// 在这里粘贴你的代码
```

**Comment by buuing** [comment]
可以打开啊

**Comment by buuing** [comment]
`wordWrap?: boolean` **文字自动换行** （默认为 true 开启，关闭时可以使用 \n 换行）
`lengthLimit?: string | number` **换行宽度限制** （格式为：90 | '90px' | '90%'，默认为 '90%'）

**Comment by GongZhuoYing** [comment]
还有一个问题：我的大转盘里面的奖品图片不显示，必须要先抽过奖了才显示

**Comment by buuing** [comment]
> 还有一个问题：我的大转盘里面的奖品图片不显示，必须要先抽过奖了才显示

贴一下你的代码, 我看看你怎么用的

**Comment by GongZhuoYing** [comment]
//奖品列表
      awards(){
        let arr=[];
        if(this.lotteryData.prizeList.length>0){
          this.lotteryData.prizeList.forEach((item,index) => {
            let itemData = {
              fonts:[
                {text:item.przeNm,top: 20,fontColor:'#d64737',wordWrap:'\n'}
              ],
              imgs:[
                {src:item.przePictPath,width: '30%'},
              ],
              background: (index%2 ==0) ?'#f9e3bb':'#fff' };
            arr.push(itemData);
          });
        }
        return arr;
      }

**Comment by buuing** [comment]
大哥把代码格式化一下放到代码块里面

**Comment by GongZhuoYing** [comment]
awards(){
  let arr=[];
  if(this.lotteryData.prizeList.length>0){
    this.lotteryData.prizeList.forEach((item,index) => {
      let itemData = {
        fonts:[
          {text:item.przeNm,top: 20,fontColor:'#d64737',wordWrap:` \n`}
        ],
        imgs:[
          {src:item.przePictPath,width: '30%'},
        ],
        background: (index%2 ==0) ?'#f9e3bb':'#fff' };
      arr.push(itemData);
    });
  }
  return arr;
}

**Comment by GongZhuoYing** [comment]
awards(){
       let arr=[];
  if(this.lotteryData.prizeList.length>0){
       this.lotteryData.prizeList.forEach((item,index) => {
           let itemData = {
              fonts:[
                   {text:item.przeNm,top: 20,fontColor:'#d64737',wordWrap:` \n`}
              ],
              imgs:[
                  {src:item.przePictPath,width: '30%'},
              ],
              background: (index%2 ==0) ?'#f9e3bb':'#fff' };
          arr.push(itemData);
    });
  }
  return arr;
}

**Comment by GongZhuoYing** [comment]
我都格式化了，还是这样显示

**Comment by buuing** [comment]
> 我都格式化了，还是这样显示

用代码块
```js
function fn () {
  if (true) {
    console.log(111)
  }
}

**Comment by GongZhuoYing** [comment]
function getAwards () {
        let awards=[];
        //this.lotteryData.prizeList是后端返回的奖品列表
        if(this.lotteryData.prizeList.length>0){
          this.lotteryData.prizeList.forEach((item,index) => {
            let itemData = {
              fonts:[
                {text:item.przeNm,top: 20,fontColor:'#d64737',wordWrap:` \n`,lengthLimit:'50%'}
              ],
              imgs:[
                {src:item.przePictPath,width: '30%'},
              ],
              background: (index%2 ==0) ?'#f9e3bb':'#fff' };
            awards.push(itemData);
          });
        }
      },

**Comment by buuing** [comment]
你百度一下md怎么输入代码块, 不是我为难你, 你这样代码我很难看出问题

**Comment by GongZhuoYing** [comment]
```awards(){
        let arr=[];
        if(this.lotteryData.prizeList.length>0){
          this.lotteryData.prizeList.forEach((item,index) => {
            let itemData = {
              fonts:[
                {text:item.przeNm,
                  top: 20,fontColor:'#d64737',
                  wordWrap:false,lengthLimit:'30%',
                  overflow:'hidden'}
              ],
              imgs:[
                {src:item.przePictPath,width: '30%'},
              ],
              background: (index%2 ==0) ?'#f9e3bb':'#fff' };
            arr.push(itemData);
          });
        }
        return arr;
      }```

**Comment by GongZhuoYing** [comment]
this.lotteryData.prizeList是接口返回的奖品列表，我用computed来返回大转盘需要的奖品

**Comment by buuing** [comment]
> this.lotteryData.prizeList是接口返回的奖品列表，我用computed来返回大转盘需要的奖品

先不要这样用, 你按照我文档里demo的方式来设置奖品, 这个还不至于来用computed来控制

**Comment by GongZhuoYing** [comment]
我的奖品是要后台返回的，不是固定的

**Comment by GongZhuoYing** [comment]
"vue-luck-draw": "^3.3.4",

**Comment by GongZhuoYing** [comment]
您的官方文档：https://100px.net/document/vue.html打不开
看不见您的demo

**Comment by buuing** [comment]
那你升级到`v3.3.8`试一下, `3.3.4`里面响应式处理有问题, 文档是基于`github pages`托管的, 或者是你们公司墙了我的域名, 你可以用手机热点链接试试

**Comment by GongZhuoYing** [comment]
我这边希望在大转盘或九宫格跑马灯抽奖时，奖品名称不超出宽度的90%，超出以后不换行，省略号显示。

**Comment by GongZhuoYing** [comment]
升级版本后报错了：vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in callback for watcher "prizes": "TypeError: Cannot convert undefined or null to object"

**Comment by buuing** [comment]
> 我这边希望在大转盘或九宫格跑马灯抽奖时，奖品名称不超出宽度的90%，超出以后不换行，省略号显示。

我没有做过文本溢出隐藏的处理, 我认为奖品名称显示完全更好一些

**Comment by GongZhuoYing** [comment]
升级版本后报错了：vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in callback for watcher "prizes": "TypeError: Cannot convert undefined or null to object"

**Comment by buuing** [comment]
这是个类型错误, 我建议你看一下文档demo里面的使用方式, 关于你无法打开文档的原因:
1, 可能是你们公司的网络拦截了, 你可以使用手机开热点来打开
2, 我的文档基于`github pages`, 理论上只要你可以打开github, 就能浏览我的文档

**Comment by buuing** [comment]
如果你不想办法打开文档, 后续恐怕还会有一堆问题
考虑到我还有正式工作, 并且我已经提供了非常详细的文档, 我更希望把业余时间用来给抽奖增加新功能

**Comment by GongZhuoYing** [comment]
好的，我自己看一下，谢谢

**Comment by buuing** [comment]
嗯, 我的文档写的非常详细, 你可以在里面找到你需要的, (除了未增加的功能), 目前我测试在有无梯子的情况下都可以打开 (无梯子会比较慢)

**Comment by GongZhuoYing** [comment]
好的，多谢大佬。这么晚了，打扰您了

**Comment by buuing** [comment]
> 好的，多谢大佬。这么晚了，打扰您了

没事, 我十分欢迎反馈bug
