### ISSUE TITLE
自适应下  转盘宽高如何设置

### ISSUE THREAD

**Issue by zzfc** [LuckDraw/vue-luck-draw#67]
- 版本号：vue-luck-draw@3.3.7

- 平台信息：谷歌浏览器 script引入

- 详细描述：pc下设置组件宽高为500px  切换到手机模式  太大  通过css设置会出问题  点击抽奖无效什么的

- 问题代码（最好同时包含 html 和 js）
```
// 在这里粘贴你的代码
```

**Comment by buuing** [comment]
可以用 `rem` 或 `百分比`

**Comment by zzfc** [comment]
> 可以用 `rem` 或 `百分比`

pc设置30rem = 480px 切换到h5模式  还是480px ..    百分比的话一直为1px。。 帮帮我这个后端选手呀

**Comment by buuing** [comment]
`rem布局`需要前置`flexible`, 你什么都不加肯定不生效, 建议先学习一下前端布局

**Comment by zzfc** [comment]
emmmm.. 我去看看

**Comment by zzfc** [comment]
他这个也要刷新一下才会计算呀- -

**Comment by buuing** [comment]
> 他这个也要刷新一下才会计算呀- -

为什么要刷新呢, 你是怎么写的, 代码我看看
