### ISSUE TITLE
奖品文字加 \n手动换行无效

### ISSUE THREAD

**Issue by guopc** [LuckDraw/vue-luck-draw#68]
- 版本号：

- 平台信息：

- 详细描述：

- 问题代码（最好同时包含 html 和 js）
```
// 在这里粘贴你的代码
```

**Comment by guopc** [comment]
wordWrap需要设置这个属性为fasle，是我没有看清楚

**Comment by buuing** [comment]
嗯, 用着顺手可以点个star支持一下
