### ISSUE TITLE
不能启动

### ISSUE THREAD

**Issue by Hsinlung** [LuckDraw/vue-luck-draw#71]
- 版本号：vue2.x

- 平台信息：vuetify框架

- 详细描述：
根据文档做的，启动不了，控制台$refs是空的

![image](https://user-images.githubusercontent.com/16730865/107145963-273d6f00-6980-11eb-8920-f29ce259aaf7.png)

**Comment by buuing** [comment]
贴一下代码，我看看你怎么写的

**Comment by Hsinlung** [comment]
> 贴一下代码，我看看你怎么写的

**mani.js**

`import Vue from 'vue'
import App from './App.vue'
import store from './store'
import router from './router'
import vuetify from './plugins/vuetify';
import LuckDraw from 'vue-luck-draw'

Vue.use(LuckDraw);
Vue.config.productionTip = false

new Vue({
  store,
  router,
  vuetify,
  render: h => h(App)
}).$mount('#app')
`
**about.vue**
`
<template>
  <div class="about">
    <h1>This is an about page</h1>
    
    <LuckyWheel
            width="300px"
            height="300px"
            :prizes="prizes"
            :default-style="defaultStyle"
            :blocks="blocks"
            :buttons="buttons"
            @start="startCallBack"
            @end="endCallBack"
    />
  </div>
</template>
<script>
  export default {
    data () {
      return {
        prizes: [],
        defaultStyle: {
          fontColor: '#d64737',
          fontSize: '14px'
        },
        blocks: [
          { padding: '13px', background: '#d64737' }
        ],
        buttons: [
          { radius: '50px', background: '#d64737' },
          { radius: '45px', background: '#fff' },
          { radius: '41px', background: '#f6c66f', pointer: true },
          {
            radius: '35px', background: '#ffdea0',
            imgs: [{ src: require('../assets/logo.png'), width: '65%', top: '-50%' }]
          }
        ],
      }
    },
    mounted () {
      this.getPrizesList()
    },
    methods: {
      getPrizesList () {
        const prizes = []
        let data = ['1元红包', '100元红包', '0.5元红包', '2元红包', '10元红包', '50元红包', '0.3元红包', '5元红包']
        data.forEach((item, index) => {
          prizes.push({
            title: item,
            background: index % 2 ? '#f9e3bb' : '#f8d384',
            fonts: [{ text: item, top: '10%' }],
          })
        })
        this.prizes = prizes
      },

      startCallBack () {
        console.info(this)
        this.$refs.LuckyWheel.play();
        setTimeout(() => {
          this.$refs.LuckyWheel.stop(Math.random() * 8 >> 0)
        }, 3000)
      },
      endCallBack (prize) {
        alert(`恭喜你获得${prize.title}`)
      },
    }
  }
</script>

`

**Comment by buuing** [comment]
我佛了，你这都没加ref，凭什么调用组件实例方法？当然会报错了

**Comment by buuing** [comment]
别忘了点个star支持一下

**Comment by Hsinlung** [comment]
> 别忘了点个star支持一下

光复制你vue代码了，还是前端新手，很棒的项目，已支持

**Comment by buuing** [comment]
好的👌
