### ISSUE TITLE
九宫格初始状态(没有开始) 中奖标记会默认停留在0号格子的位置，这个可以去掉吗（不要初始状态）？

### ISSUE THREAD

**Issue by LIZHIBIN513** [LuckDraw/vue-luck-draw#72]
- 版本号：

- 平台信息：

- 详细描述：

- 问题代码（最好同时包含 html 和 js）
```
// 在这里粘贴你的代码
```

**Comment by buuing** [comment]
**新版`v3.4.3`已更新**
1. 九宫格抽奖默认不显示中奖标识, 
2. stop方法传入-1时会立即停止游戏, 同时隐藏中奖标识, 并且此时end回调不会触发

**Comment by xiaochong0302** [comment]
> **新版`v3.4.3`已更新**
> 
> 1. 九宫格抽奖默认不显示中奖标识,
> 2. stop方法传入-1时会立即停止游戏, 同时隐藏中奖标识, 并且此时end回调不会触发

大佬， 用的这个引起，https://cdn.jsdelivr.net/npm/lucky-canvas@1.4/dist/lucky-canvas.umd.min.js，

照抄你的例子，第一个格子还是会选中

**Comment by buuing** [comment]
改成下面的链接, 指定`1.5.3`是最新版
https://cdn.jsdelivr.net/npm/lucky-canvas@1.5.3/dist/lucky-canvas.umd.min.js

**Comment by xiaochong0302** [comment]
> 改成下面的链接, 指定`1.5.3`是最新版
> https://cdn.jsdelivr.net/npm/lucky-canvas@1.5.3/dist/lucky-canvas.umd.min.js

多谢大佬，你是住在github吗，响应这么快？

**Comment by buuing** [comment]
我这边会收到微信提示, 可以看到
