### ISSUE TITLE
在安卓环境下奖品处出现奇怪矩形

### ISSUE THREAD

**Issue by 781499682ll** [LuckDraw/vue-luck-draw#76]
- 版本号：3.4.5

- 平台信息：红米6 Pro Android 8.1.0 微信浏览器

- 详细描述：
- 奖品（10元红包）靠近圆心处出现奇怪矩形，已知该矩形来自block  
- 且转盘开始转动时其他奖品也会出现并且闪动  
- 关闭gutter属性，矩形消失
![image](https://user-images.githubusercontent.com/43060542/113238651-c1b09380-92db-11eb-93ed-ac636b1661d1.png)

- 问题代码（最好同时包含 html 和 js）
```
// 在这里粘贴你的代码
// 相关参数如下
defaultStyle: {
      fontColor: '#000',
      fontSize: '0.24rem'
    },
    defaultConfig: {
      gutter: '2px',
      speed: '18'
    },
    blocks: [
      { padding: '10px', background: '#d64737' }
    ],
    buttons: [
      // { radius: '45px', background: '#BA3338' },
      // { radius: '35px', background: '#FDD35B' },
      // { radius: '29px', background: '#BA3338', pointer: true },
      {
        radius: '15px',
        background: '#FDD35B',
        // fonts: [{ text: `开始\n抽奖`, width: '100%', top: '-22px', fontColor: '#BA3338', fontSize: '18px', fontWeight: '600', lineHeight: '20px' }]
      }
    ],
// 奖品参数如下
{"name":"谢谢参与","id":"123","type":"2","background":"#fff","money":0,"rewardImg":null,"fonts":[{"text":"谢谢参与","top":"10%","lengthLimit":"1.08rem"}],"imgs":[{"src":"xxx.png","width":"40px","height":"40px","top":"40%"}]}
```

**Comment by buuing** [comment]
可以加我个微信`new_ldq`录个屏给我看一下吗

**Comment by buuing** [comment]
根据你的描述, 我可以简单猜测一下, gutter属性如果不为0的情况下, 内部会切换到arcTo来绘制扇形, 反之则使用arc来绘制扇形, 我觉得这应该就是问题所在, 因为在微信小程序下面, 使用arcTo绘制圆弧会在安卓手机下产生严重错乱, 这是个微信18年就确定的bug, 至今仍未修复, 微信浏览器内部好像使用的是X5内核吧

如果你无法接受那个小矩形, 那你只能取消gutter属性, 但是如果产品要求有缝隙, 你也可以和ui沟通,使用一个正圆作为背景并设置跟随旋转, 具体可参照官网demo的仿携程抽奖

**Comment by 781499682ll** [comment]
目前我的解决方案是把最外层的button用dom渲染然后覆盖在转盘上。  
因为我发现这个矩形距离圆心的位置是根据最外层button变化的。  
也就是说我只要把最外层button换成dom，再放到原来的位置就可以把这玩意儿覆盖掉了。

**Comment by 781499682ll** [comment]
🙏🙏🙏

**Comment by buuing** [comment]
好的, 用着顺手可以点个`star`支持一下
