### ISSUE TITLE
可以控制转盘的奖品吗

### ISSUE THREAD

**Issue by xjpe** [LuckDraw/vue-luck-draw#78]
- 版本号：

- 平台信息：

- 详细描述：

- 问题代码（最好同时包含 html 和 js）
```
// 在这里粘贴你的代码
```

**Comment by buuing** [comment]
为什么不可以呢, 请认真浏览官方文档

**Comment by xjpe** [comment]
我的意思是旋转停止的时候固定为某一奖励

**Comment by buuing** [comment]
> 我的意思是旋转停止的时候固定为某一奖励

看一下文档, 可以通过`stop`方法指定中奖奖品

**Comment by xjpe** [comment]
谢谢大佬，我以为在配置里了

**Comment by buuing** [comment]
> 谢谢大佬，我以为在配置里了

没事, 用着顺手可以点个`star`支持一下
