### ISSUE TITLE
轮盘使用图片背景，可以做到两张图片切换的动效吗？

### ISSUE THREAD

**Issue by lizy0329** [LuckDraw/vue-luck-draw#79]
- 版本号：3.4.5

- 平台信息：windows 10

- 详细描述：

就像轮盘周围那些灯在闪动的动效

- 问题代码（最好同时包含 html 和 js）
```
// 在这里粘贴你的代码
```

**Comment by buuing** [comment]
这个**可以放在抽奖组件的外部**，交给程序员自行控制
比如你提到的两张图片通过定时器来切换，你只需要**把抽奖组件定位过去即可**

**Comment by lizy0329** [comment]
> 这个**可以放在抽奖组件的外部**，交给程序员自行控制
> 比如你提到的两张图片通过定时器来切换，你只需要**把抽奖组件定位过去即可**

谢谢你的回答

**Comment by buuing** [comment]
没事，非常欢迎讨论功能

**Comment by lizy0329** [comment]
> 没事，非常欢迎讨论功能

不过我认为，轮盘边框闪灯这个效果大概是轮盘非常常用的一个功能，或许可以纳入到组件中

**Comment by buuing** [comment]
嗯，我考虑过这个问题，如果是由canvas加载整张背景图来频繁绘制的话，对于小程序端会很不友好（小程序端某些框架会把图片转成base64来渲染，背景图过大会导致渲染失败），后期我考虑一下这个问题吧
