### ISSUE TITLE
VUE 移动端怎么适配

### ISSUE THREAD

**Issue by Xingen123** [LuckDraw/vue-luck-draw#81]
VUE 移动端怎么适配

**Comment by buuing** [comment]
rem属性?

**Comment by Xingen123** [comment]
意思是传入rem




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hello ***@***.***&gt;; 
发送时间: 2021年6月2日(星期三) 下午3:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LuckDraw/vue-luck-draw] VUE 移动端怎么适配 (#81)





 
rem属性?

**Comment by buuing** [comment]
> 意思是传入rem

你直接用rem单位不就得了, 看一下我官网的demo, 可以传px单位, 可以传rem单位
