### ISSUE TITLE
请问h5页面在ios系统下需要点击两下转盘才能转动问题怎么解决呢？

### ISSUE THREAD

**Issue by xqp-ai** [LuckDraw/vue-luck-draw#88]
- 版本号：

- 平台信息：ios系统下会出现这个问题，安卓机正常

- 详细描述：vue项目里引入了fastclick延迟300ms的插件，注释掉这个插件ios点击就正常了，但是还想继续保留fastclick插件，请问有什么解决办法吗？

- 问题代码（最好同时包含 html 和 js）
```
// 在这里粘贴你的代码
```

**Comment by buuing** [comment]
你用的啥版本

**Comment by xqp-ai** [comment]
ios13.6




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hello ***@***.***&gt;; 
发送时间: 2021年7月9日(星期五) 上午10:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LuckDraw/vue-luck-draw] 请问h5页面在ios系统下需要点击两下转盘才能转动问题怎么解决呢？ (#88)





 
你用的啥版本

**Comment by buuing** [comment]
.......我问的是抽奖插件的版本!

**Comment by xqp-ai** [comment]
哈哈哈不好意思，抽奖插件版本是^3.4.5




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hello ***@***.***&gt;; 
发送时间: 2021年7月9日(星期五) 上午10:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LuckDraw/vue-luck-draw] 请问h5页面在ios系统下需要点击两下转盘才能转动问题怎么解决呢？ (#88)





 
.......我问的是抽奖插件的版本!

**Comment by buuing** [comment]
> 哈哈哈不好意思，抽奖插件版本是^3.4.5

代码贴给我看一下

**Comment by xqp-ai** [comment]
刚刚解决这个问题了，排查出了问题，在中奖之后弹窗那个组件的问题，换个组件就好了；
感谢作者提供了这个好用的插件




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hello ***@***.***&gt;; 
发送时间: 2021年7月9日(星期五) 上午10:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LuckDraw/vue-luck-draw] 请问h5页面在ios系统下需要点击两下转盘才能转动问题怎么解决呢？ (#88)





  
哈哈哈不好意思，抽奖插件版本是^3.4.5
  
代码贴给我看一下

**Comment by buuing** [comment]
ok, 谢谢支持
